backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: 'posts/.vuepress/public/uploads'
public_folder: '/uploads'
collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: /{{slug}}
    filter: { field: 'layout', value: 'blog' }
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Caption', name: 'caption', widget: 'string' }
      - { label: 'Publish Date', name: 'time', widget: 'datetime' }
      - { label: 'Cover Image', name: 'cover', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
